/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package seman1;

import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class llogin extends javax.swing.JFrame {

    /**
     * Creates new form ejerc06
     */
    public llogin() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsuario = new javax.swing.JTextField();
        usuario = new javax.swing.JLabel();
        password = new javax.swing.JLabel();
        resultado = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        button = new javax.swing.JButton();
        button1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 71, 224, 35));

        usuario.setText("Usuario:");
        getContentPane().add(usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 80, -1, -1));

        password.setText("Password:");
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 124, -1, -1));

        resultado.setText("Ingrese su datos");
        getContentPane().add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(184, 37, -1, -1));

        txtpassword.setText("jPasswordField1");
        getContentPane().add(txtpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 112, 224, 41));

        button.setText("Ingresar");
        button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonActionPerformed(evt);
            }
        });
        getContentPane().add(button, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 185, -1, -1));

        button1.setText("reset");
        getContentPane().add(button1, new org.netbeans.lib.awtextra.AbsoluteConstraints(301, 185, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/300281692_1090077998317738_7989456069265744322_n.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonActionPerformed

        if(txtUsuario.getText().equals("")){
            JOptionPane.showMessageDialog
            (null, "Ingrese Nombre del usuario", "sistema",
                    JOptionPane.ERROR_MENSSAGE);
            txtUsuario.requestFocus();
                    return;
        }
       
        
        if(txtpassword.getText().equals("")){
            JOptionPane.showMessageDialog
                    (null,"No olvide ingresar su clave", "SENATI", JOptionPane.ERROR_MESSAGE);
            txtpassword.requestFocus();
        }
     String Usuario,clave;
     Usuario = txtUsuario.getText();
     clave = txtpassword.getText();
     if ("SENATI".equals(Usuario) && "123".equals(clave)) {
     JOptionPane.showMessageDialog(null, "bienvenido al sistema"+ usuario);
     mdiPrincipal menu=new mdiPrincipal();
     menu.show(); 
     this.dispose();
     }else{
         JOoptionPane.showMessageDialog(null,"Usuario y/o clave Incorrecto", "SENATI", JOptionPane.ERROR_MESSAGE);
     txtUsuario.setText("");
     txtpassword.setText("");
     txtUsuario.requestFocus();
     }
     
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(llogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(llogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(llogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(llogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new llogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button;
    private javax.swing.JButton button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel password;
    private javax.swing.JLabel resultado;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JLabel usuario;
    // End of variables declaration//GEN-END:variables
}
